baseURL = "https://fc-aich.engelmann.me/"
title = "FC Aich"
theme = "ananke"
languageCode = "de-de"
defaultContentLanguage = "de"
#relativeURLs = true
#canonifyURLs = true
timeZone = "Europe/Berlin"

[pagination]
  paginate = 10

[params]
#author = "FC Aich"
description = "Offizielle Website des FC Aich – Fussball im Landkreis Fuerstenfeldbruck"
site_logo = "/img/fc-aich-logo.svg"
favicon = "favicon.ico"
custom_css = ["custom.css"]
style = "blue"
date_format = "02.01.2006"
about_us = "Der FC Aich ist ein Fussballverein im Landkreis Fuerstenfeldbruck. Von den Bambini bis zu den Alten Herren – bei uns gibt es Fussball fuer alle."
copyright = "© {{ now.Year }} FC Aich"
email = "info@fc-aich.de"

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
[[menu.main]]
    name = "News"
    url  = "/news/"
    weight = 2
[[menu.main]]
    name = "Zeitung"
    url  = "/zeitung/"
    weight = 3
[[menu.main]]
    name = "Shop"
    url  = "/shop/"
    weight = 4
[[menu.main]]
    name = "1. Mannschaft"
    url  = "/herren1/"
    weight = 6
[[menu.main]]
    name = "2. Mannschaft"
    url  = "/herren2/"
    weight = 7
[[menu.main]]
    name = "Damen"
    url  = "/damen/"
    weight = 8
[[menu.main]]
    name = "Jugend"
    url  = "/jugend/"
    weight = 9
[[menu.main]]
    name = "A-Herren"
    url  = "/ah/"
    weight = 10
[[menu.main]]
    name = "Vorstand"
    url  = "/vorstand/"
    weight = 15
[[menu.main]]
    name = "Downloads"
    url  = "/downloads/"
    weight = 18
[[menu.main]]
    name = "Kontakt"
    url  = "/kontakt/"
    weight = 20

[markup.goldmark.renderer]
unsafe = true
